/* Generated by backend/scripts/build-catalog.mjs. Edit shop/**-data.js instead. */

export const PRODUCTS = [
    {
        "id": "shirt1",
        "title": "doodler",
        "category": "shirts",
        "priceCents": 3300,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00001.webp",
        "colorIds": [
            "snow",
            "black",
            "pink",
            "red",
            "blue",
            "brown",
            "green",
            "dark-green",
            "washed-green",
            "purple",
            "dark-purple",
            "dark-blue",
            "grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00001.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler000025.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler000011.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00019.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00003.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00021.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00009.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00023.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00005.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00007.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00007.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00017.webp"
            },
            {
                "color": "dark-green",
                "colorLabel": "dark green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00015.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00003.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00005.webp"
            },
            {
                "color": "dark-purple",
                "colorLabel": "dark purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00013.webp"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00011.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00009.webp"
            }
        ]
    },
    {
        "id": "shirt2",
        "title": "poser",
        "category": "shirts",
        "priceCents": 3300,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00001.webp",
        "colorIds": [
            "snow",
            "pink",
            "blue",
            "red",
            "brown",
            "purple",
            "dark-purple",
            "dark-blue",
            "grey",
            "dark-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00003.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00003.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00013.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00005.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00007.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00007.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00009.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00009.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00011.webp"
            },
            {
                "color": "dark-purple",
                "colorLabel": "dark purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00015.webp"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00017.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00019.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00021.webp"
            }
        ]
    },
    {
        "id": "shirt3",
        "title": "adrien brody",
        "category": "shirts",
        "priceCents": 3300,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00001.webp",
        "colorIds": [
            "snow",
            "pink",
            "grey",
            "blue",
            "orange",
            "green",
            "black"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00003.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00003.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00005.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00005.webp"
            },
            {
                "color": "orange",
                "colorLabel": "orange",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00007.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00009.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3300,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00011.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 2800,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00007.webp"
            }
        ]
    },
    {
        "id": "shirt4",
        "title": "stork",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00001.webp",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "black",
            "purple",
            "red",
            "blue",
            "brown",
            "dark-brown",
            "washed-green",
            "dark-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00007.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00005.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00023.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00009.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00003.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00009.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00011.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00005.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00017.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00021.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00007.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00015.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00019.webp"
            }
        ]
    },
    {
        "id": "shirt5",
        "title": "purple people eater",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00003.webp",
        "colorIds": [
            "snow",
            "black",
            "grey",
            "green",
            "dark-brown",
            "blue",
            "purple",
            "dark-purple",
            "pink"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00003.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00003.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00001.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00001.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00005.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00007.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00009.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00009.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00011.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00007.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00015.webp"
            },
            {
                "color": "dark-purple",
                "colorLabel": "dark purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00013.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00005.webp"
            }
        ]
    },
    {
        "id": "shirt6",
        "title": "house",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00001.webp",
        "colorIds": [
            "snow",
            "red",
            "green",
            "purple",
            "grey",
            "pink",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00001.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00005.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00007.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00009.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00011.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00003.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00013.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00005.webp"
            }
        ]
    },
    {
        "id": "shirt7",
        "title": "squiggles",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /squiggles/SW_squiggles00001.webp",
        "colorIds": [],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "",
                "colorLabel": "",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /squiggles/SW_squiggles00001.webp"
            },
            {
                "color": "",
                "colorLabel": "",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/squiggles/EC_squiggles00001.webp"
            }
        ]
    },
    {
        "id": "shirt8",
        "title": "circus lion",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00001.webp",
        "colorIds": [
            "snow",
            "grey",
            "brown",
            "blue",
            "green",
            "pink",
            "purple",
            "dark-grey",
            "dark-blue",
            "dark-brown",
            "washed-green"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00001.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00003.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00015.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00007.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00005.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00011.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00013.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00003.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00019.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00017.webp"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00021.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00005.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00007.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00009.webp"
            }
        ]
    },
    {
        "id": "shirt9",
        "title": "circus crocodile",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00001.webp",
        "colorIds": [
            "snow",
            "green",
            "pink",
            "grey",
            "dark-grey",
            "purple",
            "dark-blue",
            "blue",
            "dark-brown",
            "washed-green",
            "washed-purple"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00001.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00015.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00019.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00003.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00009.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00017.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00013.webp"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00011.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00005.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00007.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00007.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00003.webp"
            },
            {
                "color": "washed-purple",
                "colorLabel": "washed purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00005.webp"
            }
        ]
    },
    {
        "id": "shirt10",
        "title": "circus elephant",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00002.webp",
        "colorIds": [
            "snow",
            "pink",
            "grey",
            "blue",
            "purple",
            "dark-blue",
            "green",
            "dark-brown",
            "washed-green",
            "dark-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00002.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00018.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00005.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00004.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00007.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00008.webp"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00006.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00016.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00012.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00003.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00014.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00010.webp"
            }
        ]
    },
    {
        "id": "shirt11",
        "title": "circus monkey",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00001.webp",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "washed-green",
            "washed-purple",
            "dark-blue",
            "purple",
            "dark-grey",
            "brown",
            "dark-brown",
            "grey",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00003.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00005.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00007.webp"
            },
            {
                "color": "washed-purple",
                "colorLabel": "washed purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00009.webp"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00011.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00013.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00015.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00017.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00023.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00007.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00019.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00021.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00005.webp"
            }
        ]
    },
    {
        "id": "shirt12",
        "title": "circus bunny",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00001.webp",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "washed-green",
            "washed-purple",
            "purple",
            "dark-grey",
            "dark-brown",
            "grey",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00009.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00015.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00003.webp"
            },
            {
                "color": "washed-purple",
                "colorLabel": "washed purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00005.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00013.webp"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00019.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00017.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00007.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00011.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00007.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00005.webp"
            }
        ]
    },
    {
        "id": "shirt13",
        "title": "circus ensemble",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00001.webp",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "brown",
            "washed-green",
            "purple",
            "dark-brown",
            "grey",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00001.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00007.webp"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00009.webp"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00003.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00013.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00007.webp"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00005.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00011.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00005.webp"
            }
        ]
    },
    {
        "id": "shirt14",
        "title": "circus outlines",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00001.webp",
        "colorIds": [
            "snow",
            "black",
            "purple",
            "green",
            "pink",
            "blue",
            "dark-brown",
            "washed-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00001.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00013.webp"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00009.webp"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00005.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00007.webp"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00007.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00009.webp"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00005.webp"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00002.webp"
            },
            {
                "color": "washed-grey",
                "colorLabel": "washed grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00011.webp"
            }
        ]
    },
    {
        "id": "shirt15",
        "title": "the essential burger",
        "category": "shirts",
        "priceCents": 3700,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00001.webp",
        "colorIds": [
            "snow",
            "red",
            "dark-green",
            "green"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00001.webp"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3200,
                "imagePath": "/assets/shop/mockups/essential cotton/hamburger/EC_hamburger00001.webp"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00005.webp"
            },
            {
                "color": "dark-green",
                "colorLabel": "dark green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00003.webp"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3700,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00007.webp"
            }
        ]
    },
    {
        "id": "print1",
        "title": "Cyanotype",
        "category": "prints",
        "priceCents": 0,
        "sizes": [],
        "imagePath": "/assets/shop/prints/cyanotype.webp",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "print2",
        "title": "Linoprint",
        "category": "prints",
        "priceCents": 0,
        "sizes": [],
        "imagePath": "/assets/shop/prints/house linoprint square.webp",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "print3",
        "title": "Digital Print",
        "category": "prints",
        "priceCents": 0,
        "sizes": [],
        "imagePath": "/assets/GalleryAssets/visual-art/IMG_0818.webp",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "more1",
        "title": "nothing",
        "category": "more",
        "priceCents": 0,
        "sizes": [],
        "imagePath": "",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    }
];
