/* Generated by backend/scripts/build-catalog.mjs. Edit shop/**-data.js instead. */

export const PRODUCTS = [
    {
        "id": "shirt1",
        "title": "doodler",
        "category": "shirts",
        "priceCents": 3600,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00001.png",
        "colorIds": [
            "snow",
            "black",
            "pink",
            "red",
            "blue",
            "brown",
            "green",
            "dark-green",
            "washed-green",
            "purple",
            "dark-purple",
            "dark-blue",
            "grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00001.png"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler000025.png"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler000011.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00019.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00003.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00021.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00009.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00023.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00005.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00007.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/doodler/EC_doodler00007.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00017.png"
            },
            {
                "color": "dark-green",
                "colorLabel": "dark green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00015.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00003.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00005.png"
            },
            {
                "color": "dark-purple",
                "colorLabel": "dark purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00013.png"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00011.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /doodler/SW_doodler00009.png"
            }
        ]
    },
    {
        "id": "shirt2",
        "title": "poser",
        "category": "shirts",
        "priceCents": 3600,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00001.png",
        "colorIds": [
            "snow",
            "pink",
            "blue",
            "red",
            "brown",
            "purple",
            "dark-purple",
            "dark-blue",
            "grey",
            "dark-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00003.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00003.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00013.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00005.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00007.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00007.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00009.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/poser/EC_poser00009.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00011.png"
            },
            {
                "color": "dark-purple",
                "colorLabel": "dark purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00015.png"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00017.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00019.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /poser/SW_poser00021.png"
            }
        ]
    },
    {
        "id": "shirt3",
        "title": "adrien brody",
        "category": "shirts",
        "priceCents": 3600,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00001.png",
        "colorIds": [
            "snow",
            "pink",
            "grey",
            "blue",
            "orange",
            "green",
            "black"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00003.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00003.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00005.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00005.png"
            },
            {
                "color": "orange",
                "colorLabel": "orange",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00007.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00009.png"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/oversized snow washed /adrien brody/SW_adrienbrody00011.png"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3000,
                "imagePath": "/assets/shop/mockups/essential cotton/adrien brody/EC_adrienbrody00007.png"
            }
        ]
    },
    {
        "id": "shirt4",
        "title": "stork",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00001.png",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "purple",
            "red",
            "blue",
            "brown",
            "dark-brown",
            "washed-green",
            "dark-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00007.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00005.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00003.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00009.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00011.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00005.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00017.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00021.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/storks/EC_stork00007.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00015.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /storks/SW_stork00019.png"
            }
        ]
    },
    {
        "id": "shirt5",
        "title": "purple people eater",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00003.png",
        "colorIds": [
            "snow",
            "black",
            "grey",
            "green",
            "dark-brown",
            "blue",
            "purple",
            "dark-purple",
            "pink"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00003.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00003.png"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00001.png"
            },
            {
                "color": "black",
                "colorLabel": "black",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00001.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00005.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00007.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00009.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00009.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00011.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00007.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00015.png"
            },
            {
                "color": "dark-purple",
                "colorLabel": "dark purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /ppe/SW_ppe00013.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/ppe/EC_ppe00005.png"
            }
        ]
    },
    {
        "id": "shirt6",
        "title": "house",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00001.png",
        "colorIds": [
            "snow",
            "red",
            "green",
            "purple",
            "grey",
            "pink",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00001.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00005.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00007.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00009.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00011.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00003.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /house1/SW_house1_00013.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/house1/EC_house1_00005.png"
            }
        ]
    },
    {
        "id": "shirt7",
        "title": "squiggles",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /squiggles/SW_squiggles00001.png",
        "colorIds": [],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "",
                "colorLabel": "",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /squiggles/SW_squiggles00001.png"
            },
            {
                "color": "",
                "colorLabel": "",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/squiggles/EC_squiggles00001.png"
            }
        ]
    },
    {
        "id": "shirt8",
        "title": "circus lion",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00001.png",
        "colorIds": [
            "snow",
            "grey",
            "brown",
            "blue",
            "green",
            "pink",
            "purple",
            "dark-grey",
            "dark-blue",
            "dark-brown",
            "washed-green"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00001.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00003.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00015.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00007.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00005.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00011.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00013.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00003.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00019.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00017.png"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00021.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00005.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c lion/EC_clion00007.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c lion/SW_clion00009.png"
            }
        ]
    },
    {
        "id": "shirt9",
        "title": "circus crocodile",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00001.png",
        "colorIds": [
            "snow",
            "green",
            "pink",
            "grey",
            "dark-grey",
            "purple",
            "dark-blue",
            "blue",
            "dark-brown",
            "washed-green",
            "washed-purple"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00001.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00015.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00019.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00003.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00009.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00017.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00013.png"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00011.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00005.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00007.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c croc/EC_ccroc00007.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00003.png"
            },
            {
                "color": "washed-purple",
                "colorLabel": "washed purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c croc/SW_ccroc00005.png"
            }
        ]
    },
    {
        "id": "shirt10",
        "title": "circus elephant",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00002.png",
        "colorIds": [
            "snow",
            "pink",
            "grey",
            "blue",
            "purple",
            "dark-blue",
            "green",
            "dark-brown",
            "washed-green",
            "dark-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00002.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00018.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00005.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00004.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00007.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00008.png"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00006.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00016.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00012.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c elephant/EC_celephant00003.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00014.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c elephant/SW_celephant00010.png"
            }
        ]
    },
    {
        "id": "shirt11",
        "title": "circus monkey",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00001.png",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "washed-green",
            "washed-purple",
            "dark-blue",
            "purple",
            "dark-grey",
            "brown",
            "dark-brown",
            "grey",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00003.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00005.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00007.png"
            },
            {
                "color": "washed-purple",
                "colorLabel": "washed purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00009.png"
            },
            {
                "color": "dark-blue",
                "colorLabel": "dark blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00011.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00013.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00015.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00017.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00023.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00007.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00019.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c monkey/SW_cmonkey00021.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c monkey/EC_cmonkey00005.png"
            }
        ]
    },
    {
        "id": "shirt12",
        "title": "circus bunny",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00001.png",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "washed-green",
            "washed-purple",
            "purple",
            "dark-grey",
            "dark-brown",
            "grey",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00009.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00015.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00003.png"
            },
            {
                "color": "washed-purple",
                "colorLabel": "washed purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00005.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00013.png"
            },
            {
                "color": "dark-grey",
                "colorLabel": "dark grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00019.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00017.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00007.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00011.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c bunny/SW_cbunny00007.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c bunny/EC_cbunny00005.png"
            }
        ]
    },
    {
        "id": "shirt13",
        "title": "circus ensemble",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00001.png",
        "colorIds": [
            "snow",
            "pink",
            "green",
            "brown",
            "washed-green",
            "purple",
            "dark-brown",
            "grey",
            "blue"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00001.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00007.png"
            },
            {
                "color": "brown",
                "colorLabel": "brown",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00009.png"
            },
            {
                "color": "washed-green",
                "colorLabel": "washed green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00003.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00013.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00007.png"
            },
            {
                "color": "grey",
                "colorLabel": "grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00005.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid/SW_cgrid00011.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid/EC_cgrid00005.png"
            }
        ]
    },
    {
        "id": "shirt14",
        "title": "circus outlines",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00001.png",
        "colorIds": [
            "snow",
            "purple",
            "green",
            "pink",
            "blue",
            "dark-brown",
            "washed-grey"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00001.png"
            },
            {
                "color": "purple",
                "colorLabel": "purple",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00005.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00007.png"
            },
            {
                "color": "pink",
                "colorLabel": "pink",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00007.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00009.png"
            },
            {
                "color": "blue",
                "colorLabel": "blue",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00005.png"
            },
            {
                "color": "dark-brown",
                "colorLabel": "dark brown",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/c grid outline/EC_cgridoutline00002.png"
            },
            {
                "color": "washed-grey",
                "colorLabel": "washed grey",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /c grid outline/SW_cgridoutline00011.png"
            }
        ]
    },
    {
        "id": "shirt15",
        "title": "the essential burger",
        "category": "shirts",
        "priceCents": 4200,
        "sizes": [
            "S",
            "M",
            "L",
            "XL"
        ],
        "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00001.png",
        "colorIds": [
            "snow",
            "red",
            "dark-green",
            "green"
        ],
        "materialIds": [
            "snow-washed",
            "essential-cotton"
        ],
        "variants": [
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00001.png"
            },
            {
                "color": "snow",
                "colorLabel": "snow",
                "material": "essential-cotton",
                "materialLabel": "essential cotton",
                "priceCents": 3600,
                "imagePath": "/assets/shop/mockups/essential cotton/hamburger/EC_hamburger00001.png"
            },
            {
                "color": "red",
                "colorLabel": "red",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00005.png"
            },
            {
                "color": "dark-green",
                "colorLabel": "dark green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00003.png"
            },
            {
                "color": "green",
                "colorLabel": "green",
                "material": "snow-washed",
                "materialLabel": "oversized snow washed",
                "priceCents": 4200,
                "imagePath": "/assets/shop/mockups/oversized snow washed /hamburger/SW_hamburger00007.png"
            }
        ]
    },
    {
        "id": "print1",
        "title": "Cyanotype",
        "category": "prints",
        "priceCents": 1500,
        "sizes": [],
        "imagePath": "/assets/GalleryAssets/visual-art/ArtPiece.png",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "print2",
        "title": "Linoprint",
        "category": "prints",
        "priceCents": 1500,
        "sizes": [],
        "imagePath": "",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "Digital Print",
        "title": "Print 3",
        "category": "prints",
        "priceCents": 1500,
        "sizes": [],
        "imagePath": "",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "more1",
        "title": "bbb",
        "category": "more",
        "priceCents": 1000,
        "sizes": [],
        "imagePath": "/assets/images/Package.png",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "more2",
        "title": "aaa",
        "category": "more",
        "priceCents": 1000,
        "sizes": [],
        "imagePath": "",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    },
    {
        "id": "more3",
        "title": "More 3",
        "category": "more",
        "priceCents": 1000,
        "sizes": [],
        "imagePath": "",
        "colorIds": [],
        "materialIds": [],
        "variants": []
    }
];
